// <auto-generated />
using JustShortIt.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustShortIt.Migrations
{
    [DbContext(typeof(JustShortItDbContext))]
    [Migration("20260507170403_AddRedirectClickTrackingAndCreatedAtUtc")]
    partial class AddRedirectClickTrackingAndCreatedAtUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("JustShortIt.Model.Database.BlockedRedirectId", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("blocked_redirect_ids", (string)null);
                });

            modelBuilder.Entity("JustShortIt.Model.Database.RedirectClickEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ClickedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clicked_at_utc");

                    b.Property<string>("RedirectId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("redirect_id");

                    b.Property<string>("Referrer")
                        .HasMaxLength(3072)
                        .HasColumnType("TEXT")
                        .HasColumnName("referrer");

                    b.HasKey("Id");

                    b.HasIndex("RedirectId", "ClickedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_redirect_click_events_redirect_id_clicked_at_utc");

                    b.ToTable("redirect_click_events", (string)null);
                });

            modelBuilder.Entity("JustShortIt.Model.Database.StoredUrlRedirect", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("unixepoch('now')");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(3072)
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("redirects", (string)null);
                });

            modelBuilder.Entity("JustShortIt.Model.Database.RedirectClickEvent", b =>
                {
                    b.HasOne("JustShortIt.Model.Database.StoredUrlRedirect", "Redirect")
                        .WithMany("ClickEvents")
                        .HasForeignKey("RedirectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Redirect");
                });

            modelBuilder.Entity("JustShortIt.Model.Database.StoredUrlRedirect", b =>
                {
                    b.Navigation("ClickEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
