// <auto-generated />
using JustShortIt.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustShortIt.Migrations
{
    [DbContext(typeof(JustShortItDbContext))]
    [Migration("20260507153508_AddIndexes")]
    partial class AddIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("JustShortIt.Model.Database.BlockedRedirectId", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("blocked_redirect_ids", (string)null);
                });

            modelBuilder.Entity("JustShortIt.Model.Database.StoredUrlRedirect", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(3072)
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("redirects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
