name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore JustShortIt.slnx

      - name: Build
        run: dotnet build JustShortIt.slnx --no-restore -c Release

      - name: Test
        run: dotnet test --solution JustShortIt.slnx --no-build -c Release
